version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 'r00t_passw0rd'
      MYSQL_DATABASE: 'moviles_3'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passw0rd'
